dateModified: 1614253888
email:
  fromEmail: zikisa@fonk.capetown
  fromName: 'Sprig Tester'
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
system:
  edition: solo
  live: true
  name: 'Sprig Tester'
  schemaVersion: 3.6.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
