enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  bdd1cc2d-0ceb-4431-97de-3a145da2cf27:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: 'pages/{slug}'
type: channel
